"""Generate offline preview text and colors from the Windows source files.

Run from any directory with Python 3. No PowerShell code is executed. The parser
supports this project's literal display dictionaries, not arbitrary PowerShell.
"""

import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent.parent
APP = ROOT / 'WFW_Update_Assistent 3' / 'Programm'
OUTPUT = Path(__file__).resolve().parent

# Quoted values may contain doubled quote escapes and PowerShell newline escapes.
QUOTED = r"(?:'(?:[^']|'')*'|\"(?:[^\"]|\"\")*\")"
FIELD = re.compile(r'(\w+)\s*=\s*(' + QUOTED + ')')


def decode(value):
    """Decode the string escapes used by the app's literal display data."""
    quote = value[0]
    return value[1:-1].replace(quote * 2, quote).replace('`n', '\n')


def fields(value):
    """Extract string-valued fields without evaluating PowerShell expressions."""
    return {name: decode(text) for name, text in FIELD.findall(value)}


def read_steps(source):
    """Read German then English step records, allowing multiline formatting."""
    # Consume quoted text atomically so braces and semicolons in copy stay literal.
    pattern = (
        r'@\{\s*Title\s*=\s*(' + QUOTED + r')\s*;\s*'
        r'Mode\s*=\s*(' + QUOTED + r')\s*;\s*'
        r'Text\s*=\s*(' + QUOTED + r')\s*;\s*'
        r'Actions\s*=\s*@\((.*?)\)\s*;\s*'
        r'Manual\s*=\s*\$(true|false)\s*\}'
    )
    action_pattern = (
        r'@\{\s*Id\s*=\s*(' + QUOTED + r')\s*;\s*'
        r'Label\s*=\s*(' + QUOTED + r')\s*\}'
    )
    steps = []
    for title, mode, text, actions, manual in re.findall(pattern, source, re.S):
        steps.append({
            'Title': decode(title),
            'Mode': decode(mode),
            'Text': decode(text),
            'Actions': [
                {'Id': decode(action_id), 'Label': decode(label)}
                for action_id, label in re.findall(action_pattern, actions, re.S)
            ],
            'Manual': manual == 'true',
        })
    if len(steps) != 16 or any(not step['Actions'] for step in steps):
        raise ValueError('Expected eight German and eight English steps with actions.')
    return {'de': steps[:8], 'en': steps[8:]}


def read_translations(source):
    """Read the two UI dictionaries; ignore unrelated action-message tables."""
    ui = source.split('$script:UiText = @{', 1)[1].split('$script:Steps =', 1)[0]
    translations = re.findall(r'(de|en)\s*=\s*@\{\s*\n(.*?)\n\s*\}', ui, re.S)
    if len(translations) != 2 or {lang for lang, _ in translations} != {'de', 'en'}:
        raise ValueError('Expected German and English UI translation dictionaries.')
    return {lang: fields(text) for lang, text in translations}


def build():
    """Write checked-in assets so opening the preview requires no build step."""
    source = (APP / 'Update-Assistent.ps1').read_text(encoding='utf-8-sig')
    data = {'steps': read_steps(source), 'ui': read_translations(source)}
    data_header = '// Generated by build.py from the Windows UI text. Do not edit directly.\n'
    (OUTPUT / 'data.js').write_text(
        data_header + 'const DATA = ' + json.dumps(data, ensure_ascii=False, indent=2) + ';\n',
        encoding='utf-8',
    )

    # WPF brush references are resolved by CSS variables with the same color names.
    theme = ET.parse(APP / 'Oberflaeche' / 'Theme.xaml')
    key_attribute = '{http://schemas.microsoft.com/winfx/2006/xaml}Key'
    colors = {
        element.attrib[key_attribute]: element.text
        for element in theme.getroot()
        if element.tag.endswith('}Color')
    }
    # Eight-digit WPF colors use ARGB, unlike CSS RGBA; omit the unused shadow token.
    declarations = ''.join(
        f'  --{key}: {value};\n'
        for key, value in colors.items()
        if len(value) == 7
    )
    (OUTPUT / 'theme.css').write_text(
        '/* Generated by build.py from Theme.xaml. Do not edit directly. */\n'
        + ':root {\n' + declarations + '}\n',
        encoding='utf-8',
    )
    print('Updated preview text and colors from Windows sources.')


if __name__ == '__main__':
    build()
