// Generated by build.py from the Windows UI text. Do not edit directly.
const DATA = {
  "steps": {
    "de": [
      {
        "Title": "1 · Windows aktualisieren",
        "Mode": "Der Assistent sucht und installiert für Sie",
        "Text": "Willkommen! Gehen Sie die acht Schritte nacheinander durch. Es startet nichts, bevor Sie eine Aktion auswählen und bestätigen.\n\n1. Speichern Sie Ihre Dokumente und schließen Sie andere Programme.\n2. Schließen Sie das Ladekabel an und verbinden Sie den Computer mit dem Internet.\n3. Klicken Sie auf «Windows-Updates starten» und lesen Sie die Rückfrage.\n\nFalls ein Neustart nötig ist, startet der Computer nach 120 Sekunden neu. «Neustart verschieben» stoppt den Countdown. Melden Sie sich danach wieder an und prüfen Sie Windows hier erneut.",
        "Actions": [
          {
            "Id": "Windows",
            "Label": "Windows-Updates starten"
          },
          {
            "Id": "WindowsUpdate",
            "Label": "Windows Update selbst öffnen"
          }
        ],
        "Manual": false
      },
      {
        "Title": "2 · Geräte und Treiber",
        "Mode": "Sie prüfen die Angebote in einem Windows-Fenster",
        "Text": "Treiber helfen Windows, Geräte wie Bildschirm, Drucker und Lautsprecher zu verwenden.\n\n1. Klicken Sie auf «Optionale Updates öffnen».\n2. Öffnen Sie dort «Treiberupdates», falls dieser Eintrag angezeigt wird.\n3. Installieren Sie nur Treiber, die Sie benötigen. Sind Sie unsicher, fragen Sie IT Germany.\n4. Warten Sie, bis die Installation beendet ist. Kehren Sie dann hierher zurück und setzen Sie unten das Häkchen.\n\nKeine Treiber angeboten? Dann können Sie die Prüfung ebenfalls bestätigen.",
        "Actions": [
          {
            "Id": "Treiber",
            "Label": "Optionale Updates öffnen"
          }
        ],
        "Manual": true
      },
      {
        "Title": "3 · Apps aus dem Store",
        "Mode": "Sie aktualisieren Apps im Microsoft Store",
        "Text": "Der Microsoft Store ist das Windows-Programm zum Herunterladen und Aktualisieren von Apps.\n\n1. Klicken Sie auf «Microsoft Store öffnen».\n2. Wählen Sie im Store «Downloads» oder «Bibliothek».\n3. Klicken Sie auf «Updates abrufen» beziehungsweise «Alle aktualisieren», wenn angeboten.\n4. Warten Sie, bis die Updates fertig sind. Kehren Sie hierher zurück und setzen Sie unten das Häkchen.\n\nWenn alle Apps aktuell sind, ist dieser Schritt ebenfalls erledigt.",
        "Actions": [
          {
            "Id": "Store",
            "Label": "Microsoft Store öffnen"
          }
        ],
        "Manual": true
      },
      {
        "Title": "4 · Andere Programme",
        "Mode": "Erst suchen, dann die Installation starten",
        "Text": "Hier prüft der Assistent weitere unterstützte Programme, zum Beispiel Browser.\n\n1. Klicken Sie auf «1. Nach Updates suchen». Die Suche installiert noch nichts.\n2. Lesen Sie das Ergebnis. Unter «Details zum Vorgang» sehen Sie die Programmliste.\n3. Speichern Sie Ihre Arbeit und schließen Sie die betroffenen Programme.\n4. Klicken Sie auf «2. Programme aktualisieren», sobald die Suche Updates gefunden hat.\n\nDie zweite Schaltfläche bleibt bis dahin grau. Nicht jedes Programm kann automatisch aktualisiert werden.",
        "Actions": [
          {
            "Id": "Scan",
            "Label": "1. Nach Updates suchen"
          },
          {
            "Id": "Install",
            "Label": "2. Programme aktualisieren"
          }
        ],
        "Manual": false
      },
      {
        "Title": "5 · Aufräumen (optional)",
        "Mode": "Sie können diesen Schritt auslassen",
        "Text": "Hier können Sie Programme entfernen, die Sie nicht mehr brauchen. Das ist für die Updates nicht erforderlich.\n\n1. Wenn Sie aufräumen möchten, klicken Sie auf «Installierte Apps öffnen».\n2. Suchen Sie ein bekanntes, nicht mehr benötigtes Programm.\n3. Öffnen Sie die drei Punkte daneben und wählen Sie «Deinstallieren».\n\nSie kennen ein Programm nicht? Lassen Sie es installiert.\n\nWenn Sie nichts entfernen möchten, gehen Sie einfach zum nächsten Schritt. Wenn Sie aufgeräumt haben, bestätigen Sie es unten.",
        "Actions": [
          {
            "Id": "Apps",
            "Label": "Installierte Apps öffnen"
          },
          {
            "Id": "ControlPanel",
            "Label": "Alternative Programmliste öffnen"
          }
        ],
        "Manual": true
      },
      {
        "Title": "6 · Virenschutz",
        "Mode": "Der Assistent aktualisiert den Windows-Virenschutz",
        "Text": "Microsoft Defender ist der in Windows enthaltene Virenschutz. Neue Schutzinformationen helfen ihm, aktuelle Bedrohungen zu erkennen.\n\n1. Klicken Sie auf «Virenschutz aktualisieren».\n2. Warten Sie auf das Ergebnis unten.\n3. Öffnen Sie danach «Windows-Sicherheit öffnen» und beachten Sie dort angezeigte Hinweise.\n\nNutzen Sie einen anderen Virenschutz? Öffnen Sie stattdessen dessen Programm und aktualisieren Sie ihn dort. Der Assistent wechselt Ihren Virenschutz nicht.",
        "Actions": [
          {
            "Id": "Defender",
            "Label": "Virenschutz aktualisieren"
          },
          {
            "Id": "Security",
            "Label": "Windows-Sicherheit öffnen"
          }
        ],
        "Manual": false
      },
      {
        "Title": "7 · Lenovo-Gerät",
        "Mode": "Sie prüfen Geräteupdates im Lenovo-Programm",
        "Text": "Dieser Schritt ist für Computer von Lenovo. Bei einem anderen Hersteller gehen Sie zum nächsten Schritt.\n\n1. Klicken Sie auf «Lenovo Vantage öffnen». Wenn Sie bereits System Update nutzen, öffnen Sie stattdessen dieses Programm.\n2. Fehlt das Programm? Installieren Sie eines der beiden Lenovo-Programme über die passende Schaltfläche. Eines genügt. Öffnen Sie es danach.\n3. Suchen Sie im Lenovo-Programm nach Geräteupdates und folgen Sie dessen Anweisungen.\n4. Kehren Sie nach Abschluss hierher zurück und bestätigen Sie Ihre Prüfung.\n\nBei einem BIOS- oder Firmware-Update wird die Grundsoftware des Computers aktualisiert. Lassen Sie das Ladekabel angeschlossen und schalten Sie den Computer nicht aus. Bei Fragen oder einer BitLocker-Schlüsselabfrage hilft IT Germany.",
        "Actions": [
          {
            "Id": "Vantage",
            "Label": "Lenovo Vantage öffnen"
          },
          {
            "Id": "SystemUpdate",
            "Label": "System Update öffnen"
          },
          {
            "Id": "LenovoVantage",
            "Label": "Vantage installieren, falls es fehlt"
          },
          {
            "Id": "LenovoSystemUpdate",
            "Label": "System Update installieren, falls es fehlt"
          },
          {
            "Id": "LenovoSources",
            "Label": "Hilfe bei der Lenovo-Installation"
          }
        ],
        "Manual": true
      },
      {
        "Title": "8 · Zum Abschluss",
        "Mode": "Sie prüfen, ob noch etwas zu tun ist",
        "Text": "1. Klicken Sie auf «Windows Update öffnen». Beachten Sie Hinweise auf weitere Updates oder einen nötigen Neustart.\n2. Falls ein Neustart verlangt wird: Speichern Sie Ihre Arbeit. Klicken Sie unten in Windows auf Start (das Windows-Zeichen), dann auf Ein/Aus und «Neu starten».\n3. Prüfen Sie nach dem Neustart Windows-Updates erneut. Öffnen Sie den Assistenten bei Bedarf wieder über die Startdatei.\n4. Bestätigen Sie unten Ihre Abschlussprüfung. Mit «Zusammenfassung ansehen» öffnen Sie die Ergebnisse dieser Sitzung.\n\nOffene oder fehlgeschlagene Schritte bedeuten, dass noch etwas zu prüfen ist. Die Zusammenfassung ist kein Nachweis, dass der Computer vollständig geschützt ist.",
        "Actions": [
          {
            "Id": "WindowsUpdate",
            "Label": "Windows Update öffnen"
          },
          {
            "Id": "History",
            "Label": "Bisherige Updates ansehen"
          },
          {
            "Id": "Options",
            "Label": "Weitere Windows-Einstellungen"
          }
        ],
        "Manual": true
      }
    ],
    "en": [
      {
        "Title": "1 · Update Windows",
        "Mode": "The assistant searches and installs for you",
        "Text": "Welcome. Work through the eight steps one after another. Nothing starts before you choose and confirm an action.\n\n1. Save your documents and close other programs.\n2. Connect the charger and make sure the computer is online.\n3. Click \"Start Windows updates\" and read the confirmation prompt.\n\nIf a restart is required, the computer restarts after 120 seconds. \"Postpone restart\" stops the countdown. Sign in again afterwards and check Windows here again.",
        "Actions": [
          {
            "Id": "Windows",
            "Label": "Start Windows updates"
          },
          {
            "Id": "WindowsUpdate",
            "Label": "Open Windows Update"
          }
        ],
        "Manual": false
      },
      {
        "Title": "2 · Devices and drivers",
        "Mode": "You review the offered updates in a Windows window",
        "Text": "Drivers help Windows use devices such as the screen, printer, and speakers.\n\n1. Click \"Open optional updates\".\n2. Open \"Driver updates\" there if that entry is shown.\n3. Install only drivers you need. If you are unsure, ask IT Germany.\n4. Wait until installation has finished. Return here and tick the confirmation box below.\n\nNo drivers offered? You can confirm the check as well.",
        "Actions": [
          {
            "Id": "Treiber",
            "Label": "Open optional updates"
          }
        ],
        "Manual": true
      },
      {
        "Title": "3 · Apps from the Store",
        "Mode": "You update apps in Microsoft Store",
        "Text": "Microsoft Store is the Windows program for downloading and updating apps.\n\n1. Click \"Open Microsoft Store\".\n2. In Store, choose \"Downloads\" or \"Library\".\n3. Click \"Get updates\" or \"Update all\" if offered.\n4. Wait until the updates are complete. Return here and tick the confirmation box below.\n\nIf all apps are already current, this step is complete too.",
        "Actions": [
          {
            "Id": "Store",
            "Label": "Open Microsoft Store"
          }
        ],
        "Manual": true
      },
      {
        "Title": "4 · Other programs",
        "Mode": "Search first, then start installation",
        "Text": "Here the assistant checks other supported programs, for example browsers.\n\n1. Click \"1. Search for updates\". The search does not install anything yet.\n2. Read the result. Under \"Operation details\" you can see the program list.\n3. Save your work and close the affected programs.\n4. Click \"2. Update programs\" once the search has found updates.\n\nThe second button remains disabled until then. Not every program can be updated automatically.",
        "Actions": [
          {
            "Id": "Scan",
            "Label": "1. Search for updates"
          },
          {
            "Id": "Install",
            "Label": "2. Update programs"
          }
        ],
        "Manual": false
      },
      {
        "Title": "5 · Clean up (optional)",
        "Mode": "You can skip this step",
        "Text": "Here you can remove programs that you no longer need. This is not required for the updates.\n\n1. If you want to clean up, click \"Open installed apps\".\n2. Find a known program that is no longer needed.\n3. Open the three dots beside it and choose \"Uninstall\".\n\nDo not know a program? Leave it installed.\n\nIf you do not want to remove anything, simply go to the next step. If you cleaned up, confirm it below.",
        "Actions": [
          {
            "Id": "Apps",
            "Label": "Open installed apps"
          },
          {
            "Id": "ControlPanel",
            "Label": "Open alternative program list"
          }
        ],
        "Manual": true
      },
      {
        "Title": "6 · Virus protection",
        "Mode": "The assistant updates Windows virus protection",
        "Text": "Microsoft Defender is the virus protection included with Windows. New protection information helps it detect current threats.\n\n1. Click \"Update virus protection\".\n2. Wait for the result below.\n3. Then open \"Open Windows Security\" and follow any notices shown there.\n\nUsing another antivirus product? Open that program instead and update it there. The assistant does not switch your virus protection.",
        "Actions": [
          {
            "Id": "Defender",
            "Label": "Update virus protection"
          },
          {
            "Id": "Security",
            "Label": "Open Windows Security"
          }
        ],
        "Manual": false
      },
      {
        "Title": "7 · Lenovo device",
        "Mode": "You check device updates in the Lenovo program",
        "Text": "This step is for Lenovo computers. For another manufacturer, go to the next step.\n\n1. Click \"Open Lenovo Vantage\". If you already use System Update, open that program instead.\n2. Program missing? Install one of the two Lenovo programs with the matching button. One is enough. Open it afterwards.\n3. Search for device updates in the Lenovo program and follow its instructions.\n4. Return here after completion and confirm your check.\n\nA BIOS or firmware update updates the computer's basic software. Keep the charger connected and do not switch off the computer. IT Germany can help with questions or a BitLocker key prompt.",
        "Actions": [
          {
            "Id": "Vantage",
            "Label": "Open Lenovo Vantage"
          },
          {
            "Id": "SystemUpdate",
            "Label": "Open System Update"
          },
          {
            "Id": "LenovoVantage",
            "Label": "Install Vantage if missing"
          },
          {
            "Id": "LenovoSystemUpdate",
            "Label": "Install System Update if missing"
          },
          {
            "Id": "LenovoSources",
            "Label": "Help with Lenovo installation"
          }
        ],
        "Manual": true
      },
      {
        "Title": "8 · Finish",
        "Mode": "You check whether anything is still required",
        "Text": "1. Click \"Open Windows Update\". Follow notices about more updates or a required restart.\n2. If a restart is requested: Save your work. Click Start in Windows, then Power, then \"Restart\".\n3. Check Windows updates again after the restart. Open the assistant again with the start file if needed.\n4. Confirm your final check below. \"View summary\" opens this session's results.\n\nOpen or failed steps mean that something still needs to be checked. The summary is not proof that the computer is fully protected.",
        "Actions": [
          {
            "Id": "WindowsUpdate",
            "Label": "Open Windows Update"
          },
          {
            "Id": "History",
            "Label": "View previous updates"
          },
          {
            "Id": "Options",
            "Label": "More Windows settings"
          }
        ],
        "Manual": true
      }
    ]
  },
  "ui": {
    "de": {
      "InstructionsHeader": "Schritt-für-Schritt-Anleitung",
      "AlternativesHeader": "Weitere Möglichkeiten",
      "SupportHeader": "Hilfe & Dokumentation",
      "StepIntro1": "Speichern Sie Ihre Arbeit und schließen Sie das Ladekabel an. Starten Sie dann die Windows-Updates. Falls nötig, folgt ein Neustart nach 120 Sekunden; Sie können ihn verschieben.",
      "StepIntro2": "Öffnen Sie die optionalen Updates und prüfen Sie die angebotenen Treiber. Bestätigen Sie anschließend Ihre Prüfung hier.",
      "StepIntro3": "Öffnen Sie den Microsoft Store und aktualisieren Sie Ihre Apps. Bestätigen Sie danach Ihre Prüfung hier.",
      "StepIntro4": "Suchen Sie zuerst nach verfügbaren Programmupdates. Lesen Sie das Ergebnis, schließen Sie betroffene Programme und starten Sie dann die Installation.",
      "StepIntro5": "Optional: Entfernen Sie Programme, die Sie nicht mehr benötigen. Unbekannte Programme bitte behalten. Sie können diesen Schritt offen lassen.",
      "StepIntro6": "Aktualisieren Sie den Windows-Virenschutz. Prüfen Sie anschließend die Hinweise in Windows-Sicherheit unter „Weitere Möglichkeiten“.",
      "StepIntro7": "Öffnen Sie Ihr Lenovo-Programm und prüfen Sie Geräteupdates. Bei Firmware-Updates: Ladekabel angeschlossen lassen und das Gerät nicht ausschalten. Bei anderen Herstellern weitergehen.",
      "StepIntro8": "Prüfen Sie Windows Update ein letztes Mal und bestätigen Sie Ihre Abschlussprüfung. Die Zusammenfassung zeigt, was noch offen ist.",
      "WindowTitle": "WFW Update-Assistent",
      "AppTitle": "Update-Assistent",
      "AppSubtitle": "Schritt für Schritt durch die Updates – starten Sie links mit Schritt 1.",
      "LanguageLabel": "Sprache",
      "LanguageAutomation": "Sprache auswählen",
      "ProgressLabel": "Fortschritt",
      "OverallProgressAutomation": "Gesamtfortschritt",
      "NavigationAutomation": "Bereiche und Bearbeitungsstatus",
      "CurrentStatusLabel": "Aktueller Stand",
      "NextActionLabel": "Was mache ich als Nächstes?",
      "ConfirmText": "Ich habe die Prüfung im anderen Fenster abgeschlossen (auch wenn keine Updates angeboten wurden).",
      "ConfirmAutomation": "Prüfung manuell bestätigen",
      "DetailsHeader": "Details zum Vorgang",
      "DetailAutomation": "Technische Meldungen",
      "HelpText": "Anderes Fenster geöffnet? Kehren Sie über die Windows-Taskleiste zum Assistenten zurück. «Hilfe zur Bedienung» erklärt auch Fensterwechsel und Windows-Rückfragen.",
      "Back": "Zurück",
      "Next": "Weiter",
      "Guide": "Ausführliche Anleitung (PDF)",
      "Help": "Hilfe zur Bedienung",
      "Report": "Protokoll für IT",
      "CancelRestart": "Neustart verschieben",
      "Footer": "Ardawan Khosronezhad · IT Germany   |   Version 1.2 · Pilotfassung",
      "DoneProgress": "{0} von 8 Bereichen bearbeitet",
      "SectionCounter": "SCHRITT {0} VON 8",
      "Summary": "Zusammenfassung ansehen",
      "NextStep": "Nächster Schritt →",
      "ContinueOpen": "Weiter (bleibt offen) →",
      "HintCompleted": "Dieser Schritt ist bearbeitet. Sie können zum nächsten Schritt gehen.",
      "HintScanned": "Lesen Sie die Programmliste unter «Details zum Vorgang». Starten Sie danach «2. Programme aktualisieren».",
      "HintManual": "Erledigen Sie die Prüfung im geöffneten Fenster. Kehren Sie hierher zurück und setzen Sie erst dann das Häkchen. Weitergehen allein bestätigt nichts.",
      "HintAutomatic": "Beginnen Sie mit der hervorgehobenen Schaltfläche oben. Lesen Sie danach das Ergebnis hier. Weitergehen allein bestätigt nichts.",
      "HintSummary": " Die Zusammenfassung zeigt auch Schritte, die noch offen sind.",
      "Busy": "Bitte warten und den Assistenten geöffnet lassen. Sie müssen nicht erneut klicken.",
      "RunningMessage": "Bitte warten. Der Vorgang kann mehrere Minuten dauern. Lassen Sie den Assistenten geöffnet.",
      "NotStartedOrCancelled": "Der Vorgang wurde nicht gestartet oder die Administratorabfrage wurde abgebrochen. Sie können erneut starten oder die manuelle Anleitung verwenden.",
      "NotEdited": "Noch nicht bearbeitet.",
      "NotConfirmed": "Noch nicht bestätigt.",
      "ManualConfirmed": "Von Ihnen als geprüft bestätigt. Der Assistent hat diesen Schritt nicht technisch überprüft.",
      "Restore": "Willkommen zurück. Bitte Windows erneut prüfen, damit nachgelagerte Updates ebenfalls installiert werden.",
      "RestoreFailed": "Bitte Windows-Updates erneut prüfen. Die frühere Sitzung konnte nicht übernommen werden.",
      "RestartPostponed": "Neustart verschoben. Speichern Sie Ihre Arbeit und starten Sie den Rechner später selbst neu. Danach Windows erneut prüfen.",
      "Restart120": "Windows startet in 120 Sekunden neu. Speichern und schließen Sie Ihre Arbeit. Sie können den Neustart verschieben.",
      "RestartCountdown": "Automatischer Neustart in {0} Sekunden. Bitte Arbeit speichern. Mit «Neustart verschieben» stoppen Sie den Countdown.",
      "RestartStarted": "Neustart an Windows übergeben. Falls eine Anwendung ihn blockiert, speichern und schließen Sie diese. Danach gegebenenfalls über Start neu starten.",
      "ResultMissing": "Der Vorgang lieferte kein Ergebnis. Möglicherweise blockiert eine Richtlinie die Ausführung. Nutzen Sie die manuelle Anleitung; bei wiederholtem Fehler hilft IT Germany.",
      "ResultReadFailed": "Das Ergebnis konnte nicht gelesen werden. Prüfen Sie den Zustand über die manuelle Anleitung.",
      "StillRunning": "Der Vorgang läuft noch. Die Meldungen können vorübergehend nicht gelesen werden.",
      "OpenTargetFailed": "Das Fenster konnte nicht geöffnet werden. Nutzen Sie den entsprechenden Abschnitt in der Anleitung.",
      "OpenManualTitle": "Bitte manuell öffnen",
      "AlreadyOpen": "Der Update-Assistent ist bereits geöffnet. Wechseln Sie zum vorhandenen Fenster.",
      "AlreadyOpenTitle": "Bereits geöffnet",
      "StartFailedTitle": "Update-Assistent",
      "StartFailedIntro": "Der Assistent konnte nicht gestartet werden.",
      "ManualGuide": "Nutzen Sie die manuelle Anleitung.",
      "BusyClose": "Ein Update-Vorgang läuft noch. Bitte warten Sie, bis er beendet ist. Sie können dieses Fenster währenddessen minimieren.",
      "BusyCloseTitle": "Vorgang läuft",
      "ReportOpenFailed": "Das Protokoll konnte nicht geöffnet werden.",
      "ReportTitle": "Protokoll",
      "GuideOpenFailed": "Die PDF konnte nicht geöffnet werden. Öffnen Sie Anleitung.pdf im entpackten Ordner.",
      "GuideMissing": "Öffnen Sie die separat mitgelieferte PDF-Anleitung.",
      "GuideTitle": "Anleitung",
      "HelpDialog": "So verwenden Sie den Assistenten:\n\n• Beginnen Sie oben mit der farbigen Schaltfläche. Lesen Sie danach den aktuellen Stand.\n• Öffnet sich ein anderes Fenster, erledigen Sie dort die beschriebenen Schritte.\n• Zurück zum Assistenten: Klicken Sie auf sein Symbol unten in der Windows-Taskleiste. Oder halten Sie Alt gedrückt und drücken Sie Tab, bis der Assistent ausgewählt ist.\n• Eine graue Schaltfläche ist gerade nicht verfügbar. Warten Sie auf den laufenden Vorgang oder führen Sie zuerst die Suche aus.\n• Fragt Windows, ob Änderungen erlaubt sind? Prüfen Sie, ob die Abfrage zu Ihrer gerade gestarteten Aktion gehört. Wenn Ihnen die nötigen Rechte fehlen oder Sie unsicher sind, wählen Sie Nein und fragen Sie IT Germany.\n• Weitergehen markiert einen Schritt nicht als erledigt. Offene Schritte sehen Sie links.\n\nBei Problemen: Notieren Sie die Meldung. Über «Protokoll für IT» können Sie die Ergebnisdateien öffnen; es wird nichts automatisch versendet.",
      "HelpTitle": "Hilfe zur Bedienung",
      "StateOpen": "Offen",
      "StateRunning": "Läuft",
      "StateUserConfirmed": "Benutzer bestätigt",
      "StateAuto": "Automatisch bearbeitet",
      "StateCheck": "Bitte prüfen",
      "StateRestart": "Neustart nötig",
      "StateScanned": "Suche abgeschlossen",
      "StateToolReady": "Programm bereit"
    },
    "en": {
      "InstructionsHeader": "Step-by-step instructions",
      "AlternativesHeader": "More options",
      "SupportHeader": "Help & documentation",
      "StepIntro1": "Save your work and connect the charger, then start Windows updates. If needed, a restart follows after 120 seconds; you can postpone it.",
      "StepIntro2": "Open optional updates and review the available drivers. Return here to confirm your check.",
      "StepIntro3": "Open Microsoft Store and update your apps. Return here to confirm your check.",
      "StepIntro4": "Search for program updates first. Review the result, close affected programs, then start installation.",
      "StepIntro5": "Optional: Remove programs you no longer need. Keep unfamiliar programs installed. You can leave this step open.",
      "StepIntro6": "Update Windows virus protection. Then review Windows Security using the button under “More options”.",
      "StepIntro7": "Open your Lenovo program and check device updates. During firmware updates, keep the charger connected and do not turn off the device. For other manufacturers, continue.",
      "StepIntro8": "Check Windows Update once more and confirm your final check. The summary shows anything still open.",
      "WindowTitle": "WFW Update Assistant",
      "AppTitle": "Update Assistant",
      "AppSubtitle": "Step by step through the updates - start on the left with step 1.",
      "LanguageLabel": "Language",
      "LanguageAutomation": "Choose language",
      "ProgressLabel": "Progress",
      "OverallProgressAutomation": "Overall progress",
      "NavigationAutomation": "Sections and processing status",
      "CurrentStatusLabel": "Current status",
      "NextActionLabel": "What should I do next?",
      "ConfirmText": "I have completed the check in the other window (even if no updates were offered).",
      "ConfirmAutomation": "Confirm manual check",
      "DetailsHeader": "Operation details",
      "DetailAutomation": "Technical messages",
      "HelpText": "Other window open? Return to the assistant through the Windows taskbar. \"Usage help\" also explains window switching and Windows prompts.",
      "Back": "Back",
      "Next": "Next",
      "Guide": "Detailed guide (PDF)",
      "Help": "Usage help",
      "Report": "Log for IT",
      "CancelRestart": "Postpone restart",
      "Footer": "Ardawan Khosronezhad · IT Germany   |   Version 1.2 · pilot version",
      "DoneProgress": "{0} of 8 sections completed",
      "SectionCounter": "STEP {0} OF 8",
      "Summary": "View summary",
      "NextStep": "Next step →",
      "ContinueOpen": "Continue (keeps open) →",
      "HintCompleted": "This step is complete. You can go to the next step.",
      "HintScanned": "Read the program list under \"Operation details\". Then start \"2. Update programs\".",
      "HintManual": "Complete the check in the opened window. Return here and only then tick the box. Continuing alone does not confirm anything.",
      "HintAutomatic": "Start with the highlighted button above. Then read the result here. Continuing alone does not confirm anything.",
      "HintSummary": " The summary also shows steps that are still open.",
      "Busy": "Please wait and keep the assistant open. You do not need to click again.",
      "RunningMessage": "Please wait. The operation can take several minutes. Leave the assistant open.",
      "NotStartedOrCancelled": "The operation was not started or the administrator prompt was cancelled. You can start again or use the manual guide.",
      "NotEdited": "Not started yet.",
      "NotConfirmed": "Not confirmed yet.",
      "ManualConfirmed": "Confirmed by you as checked. The assistant did not technically verify this step.",
      "Restore": "Welcome back. Please check Windows again so later updates are installed too.",
      "RestoreFailed": "Please check Windows updates again. The earlier session could not be restored.",
      "RestartPostponed": "Restart postponed. Save your work and restart the computer yourself later. Then check Windows again.",
      "Restart120": "Windows restarts in 120 seconds. Save and close your work. You can postpone the restart.",
      "RestartCountdown": "Automatic restart in {0} seconds. Please save your work. Use \"Postpone restart\" to stop the countdown.",
      "RestartStarted": "Restart handed over to Windows. If an app blocks it, save and close that app. Restart from Start if needed afterwards.",
      "ResultMissing": "The operation returned no result. A policy might be blocking execution. Use the manual guide; IT Germany can help if this repeats.",
      "ResultReadFailed": "The result could not be read. Check the state using the manual guide.",
      "StillRunning": "The operation is still running. Messages may temporarily be unreadable.",
      "OpenTargetFailed": "The window could not be opened. Use the matching section in the guide.",
      "OpenManualTitle": "Open manually",
      "AlreadyOpen": "The update assistant is already open. Switch to the existing window.",
      "AlreadyOpenTitle": "Already open",
      "StartFailedTitle": "Update Assistant",
      "StartFailedIntro": "The assistant could not be started.",
      "ManualGuide": "Use the manual guide.",
      "BusyClose": "An update operation is still running. Please wait until it has finished. You can minimize this window meanwhile.",
      "BusyCloseTitle": "Operation running",
      "ReportOpenFailed": "The log could not be opened.",
      "ReportTitle": "Log",
      "GuideOpenFailed": "The PDF could not be opened. Open Anleitung.pdf in the extracted folder.",
      "GuideMissing": "Open the separately supplied PDF guide.",
      "GuideTitle": "Guide",
      "HelpDialog": "How to use the assistant:\n\n• Start with the colored button at the top. Then read the current status.\n• If another window opens, complete the steps described there.\n• Return to the assistant by clicking its icon in the Windows taskbar. Or hold Alt and press Tab until the assistant is selected.\n• A grey button is currently unavailable. Wait for the running operation or run the search first.\n• Does Windows ask whether changes are allowed? Check whether the prompt belongs to the action you just started. If you lack the required rights or are unsure, choose No and ask IT Germany.\n• Continuing does not mark a step as complete. Open steps are shown on the left.\n\nIf there are problems: Note the message. With \"Log for IT\" you can open the result files; nothing is sent automatically.",
      "HelpTitle": "Usage help",
      "StateOpen": "Open",
      "StateRunning": "Running",
      "StateUserConfirmed": "Confirmed by user",
      "StateAuto": "Automatically processed",
      "StateCheck": "Please check",
      "StateRestart": "Restart required",
      "StateScanned": "Search completed",
      "StateToolReady": "Program ready"
    }
  }
};
